# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-07 09:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='guide_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guide_name', models.CharField(default='', max_length=50)),
                ('address', models.CharField(default='', max_length=50)),
                ('work_details', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(default='', max_length=50)),
                ('password', models.CharField(default='', max_length=50)),
                ('aboutguide', models.CharField(default='', max_length=50)),
                ('company1', models.CharField(default='', max_length=50)),
                ('companyduration1', models.CharField(default='', max_length=50)),
                ('positionInCompany1', models.CharField(default='', max_length=50)),
                ('company2', models.CharField(default='', max_length=50)),
                ('companyduration2', models.CharField(default='', max_length=50)),
                ('positionInCompany2', models.CharField(default='', max_length=50)),
                ('company3', models.CharField(default='', max_length=50)),
                ('companyduration3', models.CharField(default='', max_length=50)),
                ('positionInCompany3', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='notify_me',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goaltype', models.CharField(choices=[('IAS', 'IAS'), ('IPS', 'IPS'), ('ENGINEER', 'ENGINEER'), ('DOCTOR', 'DOCTOR')], default='IAS', max_length=20)),
                ('notification', models.CharField(default='null', max_length=50)),
                ('notify', models.TextField(max_length=500)),
                ('created_on', models.DateTimeField(blank=True, default=django.utils.datetime_safe.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='scholorship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apply_scholorship', models.URLField()),
                ('goaltype', models.CharField(choices=[('IAS', 'IAS'), ('IPS', 'IPS'), ('ENGINEER', 'ENGINEER'), ('DOCTOR', 'DOCTOR')], default='ias', max_length=20)),
                ('scholorship_details', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='spons_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsor_name', models.CharField(default='', max_length=50)),
                ('address', models.CharField(default='', max_length=50)),
                ('aboutsponsor', models.CharField(default='', max_length=50)),
                ('work_details', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(default='', max_length=50)),
                ('password', models.CharField(default='', max_length=50)),
                ('company1', models.CharField(default='', max_length=50)),
                ('positionInCompany1', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='student_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(default='', max_length=50)),
                ('date_of_birth', models.CharField(default='', max_length=50)),
                ('goal', models.CharField(default='', max_length=50)),
                ('current_education', models.CharField(default='', max_length=50)),
                ('phone1', models.CharField(default='', max_length=15)),
                ('location', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(default='', max_length=50)),
                ('password', models.CharField(default='', max_length=50)),
                ('school', models.CharField(default='', max_length=50)),
                ('school_duration', models.CharField(default='', max_length=50)),
                ('school_board', models.CharField(default='', max_length=50)),
                ('school_achievements', models.CharField(default='', max_length=150)),
                ('collage1', models.CharField(default='', max_length=50)),
                ('collage_course1', models.CharField(default='', max_length=50)),
                ('collage_achievements1', models.CharField(default='', max_length=150)),
                ('collage_duration1', models.CharField(default='', max_length=50)),
                ('collage2', models.CharField(default='', max_length=50)),
                ('collage_course2', models.CharField(default='', max_length=50)),
                ('collage_achievements2', models.CharField(default='', max_length=150)),
                ('collage_duration2', models.CharField(default='', max_length=50)),
                ('docfile', models.FileField(upload_to='documents/%Y/%m/%d')),
            ],
        ),
    ]
