# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-07 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserDatabase', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_details',
            name='current_education',
        ),
        migrations.AlterField(
            model_name='student_details',
            name='docfile',
            field=models.FileField(upload_to='doc'),
        ),
    ]
