# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-07 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserDatabase', '0002_auto_20170607_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide_details',
            name='docfile',
            field=models.FileField(default='images/img_avatar2.png', upload_to='doc'),
        ),
        migrations.AddField(
            model_name='spons_details',
            name='docfile',
            field=models.FileField(default='images/img_avatar2.png', upload_to='doc'),
        ),
    ]
