# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-07 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserDatabase', '0003_auto_20170607_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spons_details',
            name='work_details',
        ),
        migrations.AddField(
            model_name='student_details',
            name='current_education',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='guide_details',
            name='docfile',
            field=models.FileField(upload_to='doc'),
        ),
        migrations.AlterField(
            model_name='spons_details',
            name='docfile',
            field=models.FileField(default='images/img_avatar2.jpg', upload_to='doc'),
        ),
    ]
