# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-07 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserDatabase', '0004_auto_20170607_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide_details',
            name='docfile',
            field=models.FileField(default='images/img_avatar2.jpg', upload_to='doc'),
        ),
    ]
