# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-07 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserDatabase', '0006_auto_20170607_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide_details',
            name='docfile',
            field=models.FileField(upload_to='sponsor'),
        ),
        migrations.AlterField(
            model_name='student_details',
            name='docfile',
            field=models.FileField(upload_to='guide'),
        ),
    ]
