# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-08 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserDatabase', '0007_auto_20170607_1818'),
    ]

    operations = [
        migrations.CreateModel(
            name='guide_inbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guide_mail', models.EmailField(default='', max_length=50)),
                ('sender_mail_1', models.EmailField(default='', max_length=50)),
                ('sender_message_1', models.CharField(default='', max_length=100)),
                ('sender_mail_2', models.EmailField(default='', max_length=50)),
                ('sender_message_2', models.CharField(default='', max_length=100)),
                ('sender_mail_3', models.EmailField(default='', max_length=50)),
                ('sender_message_3', models.CharField(default='', max_length=100)),
                ('sender_mail_4', models.EmailField(default='', max_length=50)),
                ('sender_message_4', models.CharField(default='', max_length=100)),
                ('sender_mail_5', models.EmailField(default='', max_length=50)),
                ('sender_message_5', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='sponsor_inbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsor_mail', models.EmailField(default='', max_length=50)),
                ('sender_mail_1', models.EmailField(default='', max_length=50)),
                ('sender_message_1', models.CharField(default='', max_length=100)),
                ('sender_mail_2', models.EmailField(default='', max_length=50)),
                ('sender_message_2', models.CharField(default='', max_length=100)),
                ('sender_mail_3', models.EmailField(default='', max_length=50)),
                ('sender_message_3', models.CharField(default='', max_length=100)),
                ('sender_mail_4', models.EmailField(default='', max_length=50)),
                ('sender_message_4', models.CharField(default='', max_length=100)),
                ('sender_mail_5', models.EmailField(default='', max_length=50)),
                ('sender_message_5', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='student_inbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_mail', models.EmailField(default='', max_length=50)),
                ('sender_mail_1', models.EmailField(default='', max_length=50)),
                ('sender_message_1', models.CharField(default='', max_length=100)),
                ('sender_mail_2', models.EmailField(default='', max_length=50)),
                ('sender_message_2', models.CharField(default='', max_length=100)),
                ('sender_mail_3', models.EmailField(default='', max_length=50)),
                ('sender_message_3', models.CharField(default='', max_length=100)),
                ('sender_mail_4', models.EmailField(default='', max_length=50)),
                ('sender_message_4', models.CharField(default='', max_length=100)),
                ('sender_mail_5', models.EmailField(default='', max_length=50)),
                ('sender_message_5', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
