# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-09 05:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserDatabase', '0008_guide_inbox_sponsor_inbox_student_inbox'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notify_me',
            name='goaltype',
            field=models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('MEC', 'MEC'), ('CIVIL', 'CIVIL'), ('DOCTOR', 'DOCTOR')], default='IAS', max_length=20),
        ),
        migrations.AlterField(
            model_name='scholorship',
            name='goaltype',
            field=models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('MEC', 'MEC'), ('CIVIL', 'CIVIL'), ('DOCTOR', 'DOCTOR')], default='ias', max_length=20),
        ),
    ]
