# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-09 06:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserDatabase', '0009_auto_20170609_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide_details',
            name='aboutguide',
            field=models.CharField(default='', max_length=110),
        ),
        migrations.AlterField(
            model_name='spons_details',
            name='aboutsponsor',
            field=models.CharField(default='', max_length=110),
        ),
    ]
