# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-10 05:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserDatabase', '0011_auto_20170609_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide_details',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='guide'),
        ),
    ]
