# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-10 06:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserDatabase', '0015_auto_20170610_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='certificate',
            field=models.FileField(upload_to='guide'),
        ),
    ]
